popem_api_client_login_check:
  path: /login-check
  defaults:
    _controller: AppBundle:Api/User:loginCheck
  methods: GET

popem_api_client_login:
  path: /login
  defaults:
      _controller: AppBundle:Api/User:login
  methods: [POST]

popem_api_client_register:
  path: /register
  defaults:
    _controller: AppBundle:Api/User:register
  methods: [POST]

popem_api_client_balance:
  path: /user-balance
  defaults:
    _controller: AppBundle:Api/User:clientBalance
  methods: GET

popem_api_client_deposit_account:
  path: /deposit-account
  defaults:
    _controller: AppBundle:Api/User:clientDepositAccount
  methods: POST

popem_api_client_withdrawal_account:
  path: /withdrawal-account
  defaults:
    _controller: AppBundle:Api/User:clientWithdrawalAccount
  methods: POST

popem_api_client_add_account:
  path: /add-account
  defaults:
    _controller: AppBundle:Api/User:addAccount
  methods: POST

popem_api_client_validate_account:
  path: /validate-account
  defaults:
    _controller: AppBundle:Api/User:accountValidation
  methods: POST

popem_api_client_validate:
  path: /validate-client
  defaults:
    _controller: AppBundle:Api/User:clientValidation
  methods: POST

popem_api_client_list_account:
  path: /list-account
  defaults:
    _controller: AppBundle:Api/User:listAccount
  methods: GET

popem_api_client_report_finance:
  path: /report-finance
  defaults:
    _controller: AppBundle:Api/ReportFinance:index
  methods: POST

popem_api_client_report_rebate:
  path: /report-rebate
  defaults:
    _controller: AppBundle:Api/ReportRebate:index
  methods: POST

popem_api_client_dummy:
  path: /dummy
  defaults:
    _controller: AppBundle:Api/User:dummy