popem_client_login_warp:
  path: /login
  defaults:
    _controller: AppBundle:Client/ClientLogin:index

popem_client_forgot_password:
  path: /forgot-password
  defaults:
    _controller: AppBundle:Client/PasswordForgot:passwordForgot
  methods: [GET|POST]

popem_client_reset_password:
  path: /reset
  defaults:
    _controller: AppBundle:Client/PasswordReset:passwordReset
  methods: [GET|POST]

popem_client_setting_password:
  path: /setting-password
  defaults:
    _controller: AppBundle:Client/ClientSettingPassword:index
  methods: [GET|POST]

popem_client_logout:
  path: /logout
  defaults:
    _controller: AppBundle:Client/ClientLogout:index