popem_client_index:
  path: /
  defaults:
    _controller: AppBundle:Client:home

popem_client_blog:
  path: /blog
  defaults:
    _controller: AppBundle:Client:blog

popem_client_detail_blog:
  path: /blog/{slug}
  defaults:
    _controller:  AppBundle:Client:detailBlog
  methods:  [GET]

popem_client_article:
  path: /article
  defaults:
    _controller: AppBundle:Client:article
  methods: [GET, POST]

popem_client_dashboard:
  path: /dashboard
  defaults:
    _controller: AppBundle:Client:dashboardClient

popem_client_login_auth_legacy:
  path: /loginauth
  defaults:
    _controller: AppBundle:Client:loginAuthLegacy
  methods: [POST]

popem_client_login_auth_form:
  path: /login
  defaults:
    _controller: AppBundle:Client:loginAuth
  methods: [POST]

popem_client_login_warp:
  path: /login
  defaults:
    _controller: AppBundle:Client:login

popem_client_logout:
  path: /logout
  defaults:
    _controller: AppBundle:Client:logout

popem_client_activate:
  path: /activate
  defaults:
    _controller: AppBundle:Client:activate