popem_client_index:
  path: /
  defaults:
    _controller: AppBundle:Client/ClientHome:index

popem_client_blog:
  path: /blog
  defaults:
    _controller: AppBundle:Dashboard/Blog:blog

popem_client_testing:
  path: /testing
  defaults:
    _controller:  AppBundle:Client:layout

popem_client_detail_blog:
  path: /blog/{slug}
  defaults:
    _controller:  AppBundle:Dashboard/Blog:detailBlog
  methods:  [GET]

popem_client_article:
  path: /article
  defaults:
    _controller: AppBundle:Client:article
  methods: [GET, POST]

popem_client_category:
  path: /category/{category}
  defaults:
    _controller:  AppBundle:Dashboard/Blog:blogCategory

popem_client_testimonial:
  path: /testimonial
  defaults:
    _controller: AppBundle:Client/ClientTestimonial:testimonial    

popem_client_dashboard:
  path: /client/dashboard
  defaults:
    _controller: AppBundle:Client/ClientDashboard:index

popem_client_activate:
  path: /activate
  defaults:
    _controller: AppBundle:Client/ClientActivate:activate
  methods: GET

popem_client_validate_client:
  path: /client/validate
  defaults:
    _controller: AppBundle:Client/ClientValidate:index
  methods: [GET, POST]

popem_client_list_account:
  path: /account
  defaults:
    _controller: AppBundle:Client/AccountList:index
  methods: GET

popem_client_add_account:
  path: /account/add
  defaults:
    _controller: AppBundle:Client/AccountAdd:index

popem_client_validate_account:
  path: /account/validate
  defaults:
    _controller: AppBundle:Client/AccountValidate:index

popem_client_transfer_account:
  path: /account/transfer
  defaults:
    _controller: AppBundle:Client/TransferAccount:transferAccount
  methods: GET

popem_client_transfer_from:
  path: /account/transfer-from
  defaults:
    _controller: AppBundle:Client/TransferAccount:transferFromAccount
  methods: POST

popem_client_transfer_to:
  path: /account/transfer-to
  defaults:
    _controller: AppBundle:Client/TransferAccount:transferToAccount
  methods: POST

popem_client_transfer:
  path: /transfer
  defaults:
    _controller:  AppBundle:Client/TransferClient:index
  methods:  GET

popem_client_transfer_client:
  path: /transfer/transfer-client
  defaults:
    _controller:  AppBundle:Client/TransferClient:transferClient
  methods:  POST

popem_client_withdrawal_client:
  path: /client/withdrawal
  defaults:
    _controller: AppBundle:Client/ClientWithdrawal:index
  methods: GET

popem_client_withdrawal_client_post:
  path: /client/withdrawal
  defaults:
    _controller: AppBundle:Client/ClientWithdrawal:post
  methods: POST

popem_client_deposit_client:
  path: /client/deposit
  defaults:
    _controller: AppBundle:Client/ClientDeposit:index
  methods: GET|POST

popem_client_dummy_form:
  path: /dummy
  defaults:
    _controller: AppBundle:Client:dummy

popem_auth:
  resource: "@AppBundle/Resources/config/routing/client/auth/routing.yml"
  prefix: /auth

popem_client_history:
  resource: "@AppBundle/Resources/config/routing/client/history/routing.yml"
  prefix: /client/history