popem_client_index:
  path: /
  defaults:
    _controller: AppBundle:Client:home

popem_client_blog:
  path: /blog
  defaults:
    _controller: AppBundle:Dashboard/Blog:blog

popem_client_testing:
  path: /testing
  defaults:
    _controller:  AppBundle:Client:layout

popem_client_detail_blog:
  path: /blog/{slug}
  defaults:
    _controller:  AppBundle:Dashboard/Blog:detailBlog
  methods:  [GET]

popem_client_article:
  path: /article
  defaults:
    _controller: AppBundle:Client:article
  methods: [GET, POST]

popem_client_category:
  path: /category/{category}
  defaults:
    _controller:  AppBundle:Dashboard/Blog:blogCategory

popem_client_dashboard:
  path: /client/dashboard
  defaults:
    _controller: AppBundle:Client:dashboardClient

popem_client_login_auth_legacy:
  path: /loginauth
  defaults:
    _controller: AppBundle:Client:loginAuthLegacy
  methods: [POST]

popem_client_login_auth_form:
  path: /login
  defaults:
    _controller: AppBundle:Client:loginAuth
  methods: [POST]

popem_client_login_warp:
  path: /login
  defaults:
    _controller: AppBundle:Client:login

popem_client_logout:
  path: /logout
  defaults:
    _controller: AppBundle:Client:logout

popem_client_activate:
  path: /activate
  defaults:
    _controller: AppBundle:Client:activate

popem_client_validate_client:
  path: /client/validate
  defaults:
    _controller: AppBundle:Client:validateClient
  methods: [GET, POST]

popem_client_list_account:
  path: /account
  defaults:
    _controller: AppBundle:Client:listAccount
  methods: GET

popem_client_add_account:
  path: /account/add
  defaults:
    _controller: AppBundle:Client:addAccount

popem_client_validate_account:
  path: /account/validate
  defaults:
    _controller: AppBundle:Client:validateAccount

popem_client_transfer_account:
  path: /account/transfer
  defaults:
    _controller: AppBundle:Client:transferAccount
  methods: GET

popem_client_transfer_from:
  path: /account/transfer-from
  defaults:
    _controller: AppBundle:Client:transferFromAccount
  methods: POST

popem_client_transfer_to:
  path: /account/transfer-to
  defaults:
    _controller: AppBundle:Client:transferToAccount
  methods: POST

popem_client_dummy_form:
  path: /dummy
  defaults:
    _controller: AppBundle:Client:dummy