popem_client_index:
  path: /
  defaults:
    _controller: AppBundle:Client:home

popem_client_blog:
  path: /blog
  defaults:
    _controller: AppBundle:Client:blog

popem_client_article:
  path: /article
  defaults:
    _controller: AppBundle:Client:article

popem_client_dashboard:
  path: /dashboard
  defaults:
    _controller: AppBundle:Client:dashboardClient