popem_admin_login:
  path: /login
  defaults:
    _controller: AppBundle:Admin:login
  methods:  [GET,POST]

popem_admin_register:
  path: /register
  defaults:
    _controller:  AppBundle:Admin:register
  methods: [GET,POST]

popem_admin_logout:
  path: /logout
  defaults:
    _controller:  AppBundle:Admin:logout

popem_admin_home:
    path: /home
    defaults:
      _controller:  AppBundle:Admin:home

popem_admin_new_page:
    path: /new-page
    defaults:
      _controller:  AppBundle:Admin:newPage
    methods:  [GET,POST]

popem_admin_list_page:
    path: /list-page
    defaults:
      _controller:  AppBundle:Admin:listPage

popem_admin_update_page:
    path: /update-page/{id}
    defaults:
      _controller:  AppBundle:Admin:updatePage

popem_admin_delete_page:
    path: /delete-page/{id}
    defaults:
      _controller:  AppBundle:Admin:deletePage

popem_admin_new_category:
    path: /category
    defaults:
      _controller:  AppBundle:Admin:newCategory
    methods:  [GET,POST]

popem_admin_list_category:
    path: /list-category
    defaults:
      _controller:  AppBundle:Admin:listCategory

popem_admin_delete_category:
    path: /delete-category/{id}
    defaults:
      _controller:  AppBundle:Admin:deleteCategory

popem_admin_new_post:
    path: /new-post
    defaults:
      _controller:  AppBundle:Admin:newPost
    methods:  [GET,POST]

popem_admin_list_post:
    path: /list-post
    defaults:
      _controller:  AppBundle:Admin:listPost

popem_admin_update_post:
    path: /update-post/{id}
    defaults:
        _controller:  AppBundle:Admin:updatePost

popem_admin_delete_post:
     path:  /delete-post/{id}
     defaults:
        _controller:  AppBundle:Admin:deletePost

popem_admin_new_tag:
    path: /new-tag
    defaults:
      _controller:  AppBundle:Admin:newTag
    methods:  [GET,POST]

popem_admin_list_tag:
    path: /list-tag
    defaults:
      _controller:  AppBundle:Admin:listTag

popem_admin_delete_tag:
    path: /delete-tag/{id}
    defaults:
      _controller:  AppBundle:Admin:deleteTag