popem_admin_home:
    path: /home
    defaults:
      _controller:  AppBundle:Admin:home

popem_admin_new_post:
    path: /new-post
    defaults:
      _controller:  AppBundle:Admin:post

popem_admin_list_post:
    path: /list-post
    defaults:
      _controller:  AppBundle:Admin:listPost

popem_admin_new_category:
    path: /category
    defaults:
      _controller:  AppBundle:Admin:newCategory

popem_admin_list_category:
    path: /list-category
    defaults:
      _controller:  AppBundle:Admin:listCategory

popem_admin_new_page:
    path: /new-page
    defaults:
      _controller:  AppBundle:Admin:newPage