AppBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        categoryId:
            targetEntity: Category
            joinColumn:
                name: category_id
                referencedColumns:  id
    fields:
        title:
            type: string
            length: 255
        slug:
            type: text
        image:
            type: string
            length: 255
        body:
            type: text
        tag:
            type: text
        status:
            type: integer
        metaKeyword:
            type: text
            column: meta_keyword
        metaDescription:
            type: text
            column: meta_description
        publishedAt:
            type: datetime
            column: published_at
            nullable: true
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
    lifecycleCallbacks: {  }
